export const options = [
  "-Select One-",
  "Ice/Quartz White Pearl Tricoat",
  "Century White",
  "Monaco White",
  "Powder White Pearl Tricoat",
  "Casablanca White Pearl",
  "Shimmering White",
  "Dazzling White",
  "Diamond White Pearl",
  "Noble White",
  "Ceramic White",
  "Symphony Silver Metallic",
  "Harbor Gray Metallic",
  "Shale Gray Metallic",
  "Mineral Gray Metallic",
  "Ironman/Sleek Silver Metallic",
  "Titanium Gray Metallic",
  "Shimmering Silver Metallic",
  "Galactic Gray",
  "Coliseum Gray",
  "Charming Gray Metallic",
  "Parisian Gray Metallic",
  "Triathlon Gray Metallic",
  "Empire State Gray Metallic",
  "Santiago Silver Metallic",
  "Platinum Graphite Metallic",
  "Platinum Sage Metallic",
  "Electric/Marina Blue Metallic",
  "Caribbean Blue",
  "Marathon Blue Pearl",
  "Pacific Blue Pearl",
  "Nouveau Blue Metallic",
  "Indigo Blue Pearl",
  "Pacific Blue Metallic",
  "Nightfall Blue",
  "Deepwater Blue Pearl",
  "Venetian Red Metallic",
  "Boston Red Pearl",
  "Scarlet Red Pearl",
  "Venetian Red Pearl",
  "Serrano Red Pearl",
  "Ruby Wine Tricoat",
  "Dark Cherry Red Pearl",
  "Garnet Red Pearl",
  "Tsukuba Red",
  "Black",
  "Silver",
  "Green",
  "Orange",
  "Beige",
  "Brown",
];

export const CBSAOptions = [
  "-Select One-",
  "CA DIV SAN RAMON",
  "AZ PHOENIX-MESA-SCOTTSDALE",
  "AR LITTLE ROCK NORTH LITTLE RO",
];


export const yearOptions = [
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
];
